# Generated by Django 2.0.2 on 2018-05-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=models.AutoField(primary_key=True, serialize=False), max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('length', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
