# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-07 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
