# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 16:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_auto_20180507_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='points',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[{'ele': 0, 'lat': 38.5, 'lon': -120.2}, {'ele': 0, 'lat': 40.7, 'lon': -120.95}, {'ele': 0, 'lat': 43.252, 'lon': -126.453}]),
        ),
    ]
