# Generated by Django 2.0.2 on 2018-05-09 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0005_auto_20180508_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
