# Generated by Django 2.0.2 on 2018-05-09 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0007_auto_20180509_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
