# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-14 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0008_auto_20180509_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(default='edit', max_length=50)),
                ('pk_route', models.PositiveIntegerField(default=0)),
                ('num_version', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
